name: Doculex AI API Deployment

on:
    push:
      branches:
        - main

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

            - name: Install Go
              uses: actions/setup-go@v3
              with:
                go-version: 1.20.5

            - name: Setup Docker BuildX
              uses: docker/setup-buildx-action@v1

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/doculex-ai-api:latest

    deployment:
        needs: release
        runs-on: ubuntu-latest
        steps:
            - name: Deployment to VPS
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.PRIVATE_KEY }}
                port: ${{ secrets.PORT }}
                script: |
                  docker stop doculex-ai-api || true
                  docker rm doculex-ai-api || true
                  docker pull ${{ secrets.DOCKER_USERNAME }}/doculex-ai-api:latest
                  docker run -d --name doculex-ai-api -p 8000:8080 \
                    -e DATABASE_URL=${{ service.app.environment.DATABASE_URL }} \
                    -e DATABASE_NAME=${{ service.app.environment.DATABASE_NAME }} \
                    -e OPENAI_API_KEY=${{ service.app.environment.OPENAI_API_KEY }} \
                    -e JWT_KEY=${{ service.app.environment.JWT_KEY }} \
                    ${{ secrets.DOCKER_USERNAME }}/doculex-ai-api:latest
                  
  